version: "1"
rules:
  - base: master
    upstream: Yggdroot:master 
    mergeMethod: merge
    assignees:              # Optional
      - lu5je0
    reviewers:              # Optional
      - lu5je0
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - lu5je0
